# 数据库
spring:
  datasource:
    username: #
    password: #
    url: #
    driver-class-name: com.mysql.cj.jdbc.Driver
    # redis配置
  redis:
    host: redis
    port: 6379
    password: #
  #    下面两个是为了遇到错误返回json
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# Mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cvc.cvcms.pojo
  configuration:
    map-underscore-to-camel-case: true

# 编码格式
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# jwt设置
jwt:
  secret: efwsa684w8e84wyriuhuaku8
  expiration: 86400000
  header: JWTToken

ftp:
  host: #
  port: #
  username: #
  password: #
  dir: #

# 微信小程序参数
wechat:
  appid: #
  secret: #
  grant_type: #
  login_url: #

# 保存日志
logging:
  file:
    name: #
